-- femboy_hyprland.lua
-- Pastel Hyprland config generator for Arch Linux.
--
-- Important:
-- Hyprland does not read Lua configs directly. This file generates
-- ~/.config/hypr/hyprland.conf, which is the config file Hyprland uses.
--
-- For your setup:
-- - Use this when Hyprland is started as a normal desktop session
--   from a display manager/login screen.
-- - This file does not try to start Hyprland from TTY.
--
-- Usage on Arch:
--   mkdir -p ~/.config/hypr
--   lua femboy_hyprland.lua > ~/.config/hypr/hyprland.conf
--   hyprctl reload
--
-- Suggested packages:
--   sudo pacman -S lua kitty wofi waybar mako swww grim slurp wl-clipboard \
--     xdg-desktop-portal-hyprland hyprpolkitagent qt5-wayland qt6-wayland \
--     brightnessctl playerctl pavucontrol network-manager-applet firefox dolphin

local cfg = {
  mod = "SUPER",
  terminal = "kitty",
  launcher = "wofi --show drun",
  browser = "firefox",
  files = "dolphin",
  wallpaper = "~/Pictures/wallpapers/cute.png",
  keyboard_layout = "pl",
}

local theme = {
  pink = "ff8ac7",
  pink2 = "ff5fbf",
  lavender = "c9a7ff",
  blue = "9bdcff",
  mint = "a8ffd6",
  dark = "241b30",
  inactive = "5a466b",
}

local function p(line)
  print(line or "")
end

local function block(name, lines)
  p(name .. " {")
  for _, line in ipairs(lines) do
    p("    " .. line)
  end
  p("}")
  p()
end

p("# Generated by femboy_hyprland.lua")
p("# Cute pastel Hyprland config for Arch Linux.")
p("# Put the generated file at: ~/.config/hypr/hyprland.conf")
p()

p("# ---------- Basic apps ----------")
p("$mod = " .. cfg.mod)
p("$terminal = " .. cfg.terminal)
p("$launcher = " .. cfg.launcher)
p("$browser = " .. cfg.browser)
p("$files = " .. cfg.files)
p()

p("# ---------- Monitor ----------")
p("# Arch/Hyprland default-friendly: use preferred mode, automatic position, scale 1.")
p("# Change this if you know your monitor name, e.g. monitor = DP-1,2560x1440@144,0x0,1")
p("monitor = ,preferred,auto,1")
p()

p("# ---------- Desktop-session autostart ----------")
p("# For Hyprland launched from a display manager/login screen.")
p("# No TTY start commands here.")
p("exec-once = systemctl --user start hyprpolkitagent")
p("exec-once = waybar")
p("exec-once = mako")
p("exec-once = nm-applet --indicator")
p("exec-once = swww-daemon")
p("exec-once = sleep 1 && swww img " .. cfg.wallpaper .. " --transition-type wipe --transition-duration 1")
p()

p("# ---------- Wayland app compatibility ----------")
p("# These are safe for a Hyprland desktop session and help common apps use Wayland.")
p("env = XDG_CURRENT_DESKTOP,Hyprland")
p("env = XDG_SESSION_DESKTOP,Hyprland")
p("env = QT_QPA_PLATFORM,wayland;xcb")
p("env = GDK_BACKEND,wayland,x11")
p("env = SDL_VIDEODRIVER,wayland")
p("env = MOZ_ENABLE_WAYLAND,1")
p("env = ELECTRON_OZONE_PLATFORM_HINT,auto")
p()

block("input", {
  "kb_layout = " .. cfg.keyboard_layout,
  "follow_mouse = 1",
  "sensitivity = 0",
  "accel_profile = flat",
  "touchpad {",
  "    natural_scroll = true",
  "    tap-to-click = true",
  "    drag_lock = 1",
  "    scroll_factor = 0.45",
  "}",
})

p("# Touchpad gesture: current Hyprland syntax.")
p("gesture = 3, horizontal, workspace")
p()

block("general", {
  "gaps_in = 6",
  "gaps_out = 14",
  "border_size = 3",
  "col.active_border = rgba(" .. theme.pink .. "ff) rgba(" .. theme.lavender .. "ff) rgba(" .. theme.blue .. "ff) 45deg",
  "col.inactive_border = rgba(" .. theme.inactive .. "aa)",
  "resize_on_border = true",
  "allow_tearing = false",
  "layout = dwindle",
})

block("decoration", {
  "rounding = 16",
  "active_opacity = 0.96",
  "inactive_opacity = 0.88",
  "fullscreen_opacity = 1.0",
  "shadow {",
  "    enabled = true",
  "    range = 18",
  "    render_power = 3",
  "    color = rgba(" .. theme.pink .. "55)",
  "    color_inactive = rgba(" .. theme.dark .. "55)",
  "}",
  "blur {",
  "    enabled = true",
  "    size = 7",
  "    passes = 3",
  "    new_optimizations = true",
  "    ignore_opacity = true",
  "}",
})

block("animations", {
  "enabled = true",
  "bezier = soft, 0.16, 1, 0.3, 1",
  "bezier = cute, 0.22, 0.9, 0.28, 1.05",
  "animation = windows, 1, 4, soft, popin 88%",
  "animation = windowsOut, 1, 3, soft, popin 80%",
  "animation = border, 1, 8, cute",
  "animation = borderangle, 1, 8, cute",
  "animation = fade, 1, 4, soft",
  "animation = workspaces, 1, 4, soft, slide",
})

block("dwindle", {
  "pseudotile = true",
  "preserve_split = true",
  "smart_split = true",
})

block("misc", {
  "disable_hyprland_logo = true",
  "disable_splash_rendering = true",
  "vfr = true",
  "mouse_move_enables_dpms = true",
  "key_press_enables_dpms = true",
})

p("# ---------- Window rules ----------")
p("windowrulev2 = float,class:^(pavucontrol)$")
p("windowrulev2 = size 900 600,class:^(pavucontrol)$")
p("windowrulev2 = center,class:^(pavucontrol)$")
p("windowrulev2 = float,class:^(blueman-manager)$")
p("windowrulev2 = float,class:^(nm-connection-editor)$")
p("windowrulev2 = float,title:^(Picture-in-Picture)$")
p("windowrulev2 = pin,title:^(Picture-in-Picture)$")
p("windowrulev2 = opacity 0.94 0.86,class:^(kitty)$")
p()

p("# ---------- Layer rules ----------")
p("layerrule = blur, waybar")
p("layerrule = blur, wofi")
p("layerrule = ignorezero, waybar")
p()

p("# ---------- Keybinds ----------")
p("bind = $mod, Return, exec, $terminal")
p("bind = $mod, Space, exec, $launcher")
p("bind = $mod, B, exec, $browser")
p("bind = $mod, E, exec, $files")
p("bind = $mod, Q, killactive")
p("bind = $mod SHIFT, Q, exit")
p("bind = $mod, F, fullscreen")
p("bind = $mod, V, togglefloating")
p("bind = $mod, T, pseudo")
p("bind = $mod, S, togglesplit")
p("bind = $mod, P, exec, pavucontrol")
p()

p("# Focus")
p("bind = $mod, H, movefocus, l")
p("bind = $mod, L, movefocus, r")
p("bind = $mod, K, movefocus, u")
p("bind = $mod, J, movefocus, d")
p()

p("# Move windows")
p("bind = $mod SHIFT, H, movewindow, l")
p("bind = $mod SHIFT, L, movewindow, r")
p("bind = $mod SHIFT, K, movewindow, u")
p("bind = $mod SHIFT, J, movewindow, d")
p()

p("# Resize windows")
p("binde = $mod CTRL, H, resizeactive, -30 0")
p("binde = $mod CTRL, L, resizeactive, 30 0")
p("binde = $mod CTRL, K, resizeactive, 0 -30")
p("binde = $mod CTRL, J, resizeactive, 0 30")
p()

p("# Workspaces")
for i = 1, 10 do
  local key = i == 10 and "0" or tostring(i)
  p("bind = $mod, " .. key .. ", workspace, " .. i)
  p("bind = $mod SHIFT, " .. key .. ", movetoworkspace, " .. i)
end
p("bind = $mod, mouse_down, workspace, e+1")
p("bind = $mod, mouse_up, workspace, e-1")
p()

p("# Screenshots")
p("bind = , Print, exec, grim -g \"$(slurp)\" - | wl-copy")
p("bind = SHIFT, Print, exec, mkdir -p ~/Pictures/Screenshots && grim ~/Pictures/Screenshots/shot-$(date +%Y%m%d-%H%M%S).png")
p()

p("# Audio, brightness, media")
p("bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+")
p("bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")
p("bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
p("bind = , XF86MonBrightnessUp, exec, brightnessctl set +8%")
p("bind = , XF86MonBrightnessDown, exec, brightnessctl set 8%-")
p("bind = , XF86AudioPlay, exec, playerctl play-pause")
p("bind = , XF86AudioNext, exec, playerctl next")
p("bind = , XF86AudioPrev, exec, playerctl previous")
p()

p("# Mouse controls")
p("bindm = $mod, mouse:272, movewindow")
p("bindm = $mod, mouse:273, resizewindow")
p()

p("# End of generated cute config.")

return {
  config = cfg,
  theme = theme,
}
