font=Noto Sans 10
width=360
height=110
margin=12
padding=12
border-size=2
border-radius=14
background-color=#2b2038ee
text-color=#fff0f8
border-color=#ff8ac7
progress-color=over #c9a7ff
default-timeout=5000
ignore-timeout=0

[urgency=low]
border-color=#9bdcff

[urgency=normal]
border-color=#ff8ac7

[urgency=high]
border-color=#ff5fbf
default-timeout=0
